package com.helpscout.demo.dynamo

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.amazonaws.services.lambda.runtime.events.models.dynamodb.AttributeValue
import com.amazonaws.services.lambda.runtime.events.transformers.v1.dynamodb.DynamodbAttributeValueTransformer
import com.helpscout.demo.CreateMessageRequest
import com.helpscout.demo.GetMessageResponse
import com.helpscout.demo.StatusCodeException

class MessageService(
    private val dynamoDBMapper: DynamoDBMapper
) {

    fun saveMessage(createMessageRequest: CreateMessageRequest): GetMessageResponse {
        val dynamoRequest = createMessageRequest.toDynamoModel()
        dynamoDBMapper.save(dynamoRequest)
        return getMessage(dynamoRequest.messageId)
    }

    fun getMessage(messageId: String): GetMessageResponse {
        val message = dynamoDBMapper.load(DynamoDBMessage(messageId = messageId))
            ?: throw StatusCodeException(
                statusCode = 404,
                error = "Message $messageId not found"
            )

        return message.fromDynamoModel()
    }

    fun changeMessageIfNeeded(newImage: GetMessageResponse, oldImage: GetMessageResponse) {
        val textToErrorOn = "That's a bad joke"
        if (newImage.body == textToErrorOn) {
            throw StatusCodeException(statusCode = 500, error = "Whoops")
        }
        val textToCheck = "Knock knock"
        if (oldImage.body != textToCheck && newImage.body == textToCheck) {
            dynamoDBMapper.save(
                DynamoDBMessage(
                    newImage.messageId,
                    messageContent = "Who's there?"
                )
            )
        }
    }

    fun covertFromAttributes(attributeValueMap: Map<String, AttributeValue>): GetMessageResponse {
        val v1AttributeValues = attributeValueMap.mapValues { (_, value) ->
            DynamodbAttributeValueTransformer.toAttributeValueV1(value)
        }
        return dynamoDBMapper
            .marshallIntoObject(DynamoDBMessage::class.java, v1AttributeValues)
            .fromDynamoModel()
    }

    private fun CreateMessageRequest.toDynamoModel(): DynamoDBMessage = DynamoDBMessage(
        messageContent = this.body
    )

    private fun DynamoDBMessage.fromDynamoModel(): GetMessageResponse = GetMessageResponse(
        messageId = this.messageId,
        body = this.messageContent
    )

    /**
     * Table name can be overwritten in mapper config
     */
    @DynamoDBTable(tableName = "local.messages")
    data class DynamoDBMessage(
        @DynamoDBHashKey(attributeName = "message_id")
        @DynamoDBAutoGeneratedKey
        var messageId: String = "",
        @DynamoDBAttribute(attributeName = "content")
        var messageContent: String = ""
    )

}