name: "Build and deploy"

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: tf-lambda-demo-terraform-state

jobs:
  build-deploy:
    name: "Build and Deploy"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Setup Gradle Wrapper
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew clean build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform format
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan -no-color -input=false

      - name: Terraform apply
        working-directory: ./terraform
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false