name: "Teardown"

on: workflow_dispatch

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_STATE: tf-lambda-demo-terraform-state

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
      - name: Setup Gradle Wrapper
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew clean build

      - uses: actions/upload-artifact@v3
        name: Save jar
        with:
          name: tf-lambda-demo
          path: build/libs/tf-lambda-demo-0-SNAPSHOT.jar

  destroy:
    name: "Destroy Terraform"
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          name: tf-lambda-demo

      - name: Set jav env
        run: echo "TF_VAR_deployable_jar=$(echo $GITHUB_WORKSPACE)/tf-lambda-demo-0-SNAPSHOT.jar" >> $GITHUB_ENV

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve -input=false